### ISSUE TITLE
Support the `[http]` table

### ISSUE THREAD

**Issue by ranger-ross** [taiki-e/cargo-config2#19]
I think adding first class support for the [`[http]`](https://doc.rust-lang.org/nightly/cargo/reference/config.html#http) table from Cargo configuration could be helpful for cargo plugins that make network calls and want to respect the Cargo HTTP config. For example [this](https://github.com/mozilla/cargo-vet/issues/612) issue in cargo-vet.

I could probably take a shot at opening a PR

**Comment by taiki-e** [comment]
I'm happy to accept a PR to implement this.
